[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
pythonpath = .
filterwarnings =
    ignore::ResourceWarning
addopts = -W ignore::ResourceWarning

[coverage:run]
source = backend
omit =
    backend/pyinstaller_entry.py
    backend/config.py
    backend/shared.py

[coverage:report]
show_missing = true
fail_under = 24
