/**
 * Smoke tests for app.js chat input wiring.
 * Run with: node tests/test_app_chat_input_wiring.js
 */

const fs = require("fs");
const path = require("path");

function collectJsFiles(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...collectJsFiles(full));
    else if (entry.isFile() && entry.name.endsWith(".js")) out.push(full);
  }
  return out;
}

const src = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "app.js"),
  "utf8"
);
const html = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "index.html"),
  "utf8"
);
const chatSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat.js"),
  "utf8"
);
const chatExportSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat_export.js"),
  "utf8"
);
const chatComposerSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat_composer_helpers.js"),
  "utf8"
);
const chatMessageActionsSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat_message_actions.js"),
  "utf8"
);
const chatMessageActionsControllerSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat_message_actions_controller.js"),
  "utf8"
);
const chatInputHelpersSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat_input_helpers.js"),
  "utf8"
);
const chatHistoryUiSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "chat_history_ui.js"),
  "utf8"
);
const memorySrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "memory.js"),
  "utf8"
);
const modalsSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "modals.js"),
  "utf8"
);
const commandsSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "commands.js"),
  "utf8"
);
const productivitySrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "productivity.js"),
  "utf8"
);
const settingsSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "settings.js"),
  "utf8"
);
const dashboardSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "dashboard.js"),
  "utf8"
);
const systemSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "system.js"),
  "utf8"
);
const preloadSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "preload.js"),
  "utf8"
);
const pluginManagerSrc = fs.readFileSync(
  path.join(__dirname, "..", "backend", "plugin_manager.py"),
  "utf8"
);
const calendarIntegrationSrc = fs.readFileSync(
  path.join(__dirname, "..", "companion", "calendar_integration.py"),
  "utf8"
);
const toolHealthSrc = fs.readFileSync(
  path.join(__dirname, "..", "companion", "tool_health.py"),
  "utf8"
);
const voiceCss = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "css", "voice.css"),
  "utf8"
);
const chatCss = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "css", "chat.css"),
  "utf8"
);
const overridesCss = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "css", "overrides.css"),
  "utf8"
);
const premiumCss = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "css", "premium_animations.css"),
  "utf8"
);
const orb3dSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "orb3d.js"),
  "utf8"
);
const i18nDe = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "i18n", "de.json"),
  "utf8"
);
const i18nEn = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "i18n", "en.json"),
  "utf8"
);
const i18nDeJson = JSON.parse(i18nDe);
const i18nEnJson = JSON.parse(i18nEn);
const i18nSrc = fs.readFileSync(
  path.join(__dirname, "..", "frontend", "src", "i18n", "i18n.js"),
  "utf8"
);
const frontendSrcDir = path.join(__dirname, "..", "frontend", "src");
const frontendJsFiles = collectJsFiles(frontendSrcDir);
const frontendMarkupFiles = [
  path.join(frontendSrcDir, "index.html"),
  ...frontendJsFiles,
];

let passed = 0;
let failed = 0;
function assert(desc, ok, detail = "") {
  if (ok) {
    console.log(`  ok: ${desc}`);
    passed += 1;
  } else {
    console.error(`  FAIL: ${desc}${detail ? " - " + detail : ""}`);
    failed += 1;
  }
}

console.log("\napp.js chat input wiring:");

const dynamicButtonCreatePattern = /document\.createElement\((["'])button\1\);/g;
const productivityButtonCreates = [...productivitySrc.matchAll(dynamicButtonCreatePattern)];
const productivityButtonsWithoutType = productivityButtonCreates.filter((match) => {
  const windowText = productivitySrc.slice(match.index, match.index + 180);
  return !/\.type\s*=\s*(["'])button\1/.test(windowText);
});
const dynamicButtonsWithoutType = [];
for (const file of frontendJsFiles) {
  const source = fs.readFileSync(file, "utf8");
  for (const match of source.matchAll(dynamicButtonCreatePattern)) {
    const windowText = source.slice(match.index, match.index + 220);
    if (!/\.type\s*=\s*(["'])button\1/.test(windowText)) {
      dynamicButtonsWithoutType.push(`${path.relative(frontendSrcDir, file)}@${match.index}`);
    }
  }
}
const staticButtonsWithoutType = [];
const staticIconButtonsWithoutName = [];
const staticFormFieldsWithoutName = [];
const missingI18nRefs = [];
const i18nDeKeys = Object.keys(i18nDeJson).sort();
const i18nEnKeys = Object.keys(i18nEnJson).sort();
const i18nKeyMismatches = [
  ...i18nDeKeys.filter((key) => !Object.prototype.hasOwnProperty.call(i18nEnJson, key)).map((key) => `de-only:${key}`),
  ...i18nEnKeys.filter((key) => !Object.prototype.hasOwnProperty.call(i18nDeJson, key)).map((key) => `en-only:${key}`),
];
const emptyI18nValues = [
  ...i18nDeKeys.filter((key) => typeof i18nDeJson[key] === "string" && i18nDeJson[key].trim() === "").map((key) => `de:${key}`),
  ...i18nEnKeys.filter((key) => typeof i18nEnJson[key] === "string" && i18nEnJson[key].trim() === "").map((key) => `en:${key}`),
];
const commandNames = [...commandsSrc.matchAll(/\bname:\s*"([^"]+)"/g)].map((match) => match[1]);
const missingCommandDescRefs = commandNames
  .map((name) => `cmd.desc.${name}`)
  .filter((key) => !Object.prototype.hasOwnProperty.call(i18nDeJson, key) || !Object.prototype.hasOwnProperty.call(i18nEnJson, key));
function noteI18nRef(key, file) {
  if (!/^[a-z0-9_.-]+$/i.test(key) || key.endsWith(".")) return;
  if (!Object.prototype.hasOwnProperty.call(i18nDeJson, key) || !Object.prototype.hasOwnProperty.call(i18nEnJson, key)) {
    missingI18nRefs.push(`${key} in ${path.relative(frontendSrcDir, file)}`);
  }
}
for (const file of frontendMarkupFiles) {
  const source = fs.readFileSync(file, "utf8");
  for (const match of source.matchAll(/data-i18n(?:-[a-z-]+)?=["']([^"']+)["']/g)) {
    noteI18nRef(match[1], file);
  }
  for (const match of source.matchAll(/\bt\(\s*["']([^"']+)["']/g)) {
    noteI18nRef(match[1], file);
  }
  for (const match of source.matchAll(/<button(?![^>]*\btype=)/g)) {
    staticButtonsWithoutType.push(`${path.relative(frontendSrcDir, file)}@${match.index}`);
  }
  for (const match of source.matchAll(/<button\b[^>]*>[\s\S]*?<\/button>/g)) {
    const htmlText = match[0];
    const openTag = htmlText.match(/^<button\b[^>]*>/)?.[0] || "";
    const visibleText = htmlText
      .replace(/<svg[\s\S]*?<\/svg>/g, "")
      .replace(/<[^>]+>/g, "")
      .replace(/&[a-zA-Z0-9#]+;/g, "")
      .trim();
    const isIconish = /\b(icon|close|delete|copy|send|mic|tts|bell|swatch|dot|btn|toggle)\b/i.test(openTag);
    const hasName = /\b(aria-label|data-i18n-aria-label|aria-labelledby)=/.test(openTag);
    const hasVisibleText = /[A-Za-zÀ-ÿ0-9]/.test(visibleText);
    if (isIconish && !hasName && !hasVisibleText) {
      staticIconButtonsWithoutName.push(`${path.relative(frontendSrcDir, file)}@${match.index}`);
    }
  }
  for (const match of source.matchAll(/<(input|textarea|select)\b[^>]*>/g)) {
    const tag = match[0];
    if (/type=["'](?:hidden|checkbox|radio)["']/.test(tag)) continue;
    const id = tag.match(/\bid=["']([^"']+)/)?.[1];
    const hasName = /\b(aria-label|data-i18n-aria-label|aria-labelledby)=/.test(tag);
    const hasExplicitLabel = Boolean(id && new RegExp(`<label[^>]*for=["']${id}["']`).test(source));
    const before = source.slice(0, match.index);
    const hasWrappingLabel = before.lastIndexOf("<label") > before.lastIndexOf("</label>") && source.indexOf("</label>", match.index) !== -1;
    if (!hasName && !hasExplicitLabel && !hasWrappingLabel) {
      staticFormFieldsWithoutName.push(`${path.relative(frontendSrcDir, file)}@${match.index}`);
    }
  }
}

const inputListener = src.match(/chatInput\.addEventListener\("input", \(\) => \{[\s\S]*?\n\s*\}\);/);
assert("input listener exists", Boolean(inputListener));
assert("input listener syncs chat input size", Boolean(inputListener?.[0].includes("syncChatInputSize")));

const historyAssignments = [...src.matchAll(/_setChatInputValue\(chatInputHistory\[chatHistoryIdx\]\);[\s\S]{0,120}/g)];
assert("history recall assignment is present", historyAssignments.length >= 1);
assert("history recall syncs chat input size", src.includes("function _setChatInputValue") && src.includes("syncChatInputSize"));

const draftAssignment = src.match(/_setChatInputValue\(chatInputDraft\);[\s\S]{0,120}/);
assert("history draft restore syncs chat input size", Boolean(draftAssignment) && src.includes("function _setChatInputValue") && src.includes("syncChatInputSize"));
assert("chat input is a multiline textarea", html.includes('<textarea id="chat-input" rows="1"') && !html.includes('type="text" id="chat-input"'));
assert("enter handling supports multiline textarea escapes", src.includes("function _chatInputShouldSendOnEnter") && src.includes("e.shiftKey") && src.includes("e.isComposing") && src.includes("window.ctrlEnterMode"));
assert("arrow history respects multiline cursor boundaries", src.includes("function _chatInputAtHistoryBoundary") && src.includes("selectionStart") && src.includes("selectionEnd") && src.includes('_chatInputAtHistoryBoundary("up")') && src.includes('_chatInputAtHistoryBoundary("down")'));
assert("textarea auto grows with overflow guard", chatSrc.includes('chatInput.tagName === "TEXTAREA"') && chatSrc.includes("scrollHeight") && chatSrc.includes("maxHeight = 160") && chatSrc.includes("chatInput.rows") && chatSrc.includes('classList.toggle("is-scrollable"') && overridesCss.includes("#chat-input.is-scrollable"));

const personalOsAutoRefresh = src.match(/refreshPersonalOsView\(\{ auto: true \}\)/);
assert("personal OS interval uses non-invasive auto refresh", Boolean(personalOsAutoRefresh));

assert("wake word start validates backend active/ready status", src.includes("function _wakeWordStartOk") && src.includes("res.active !== false") && src.includes("res.ready !== false"));
assert("wake word failures mark local state inactive", src.includes("function _markWakeWordInactive") && src.includes('LexaState.set("wakeWordActive", false)'));
assert("wake word polling periodically checks backend status", src.includes("window.lexa.wakewordStatus()") && src.includes("_wakeWordNextStatusCheck"));
assert("wake word auto-init uses same start guard", src.includes("if (_wakeWordStartOk(res))"));
assert("wake word keeps persistent preference separate from runtime state", src.includes("function _wakeWordPreferenceOn") && src.includes("function _setWakeWordPreference"));
assert("wake word manual disable clears restart and preference", src.includes("_clearWakeWordRestart();") && src.includes("_setWakeWordPreference(false);"));
assert("wake word backend status loss preserves preference and restarts", src.includes("_markWakeWordInactive(_wakeWordErrorText(status), { keepPreference: true, autoRestart: true })"));
assert("wake word backend reconnect immediately adopts desired runtime", src.includes('await _ensureWakeWordRunning("Backend healthy")'));
assert("wake word event poll reconciles renderer runtime drift", src.includes('await _ensureWakeWordRunning("Wake poll adoption")') && src.includes("if (!_wakeWordPreferenceOn()) return"));
assert("wake word start requests are singleflight guarded", src.includes("let _wakeWordStartPromise") && src.includes("async function _startWakeWordOnce") && src.includes("if (_wakeWordStartPromise) return _wakeWordStartPromise") && src.includes("return window.lexa.wakewordStart()") && src.includes("const res = await _startWakeWordOnce()"));
assert("voice orb is keyboard focusable and named", html.includes('id="voice-orb-canvas" data-action="startOrbConversation" role="button" tabindex="0" aria-pressed="false"') && html.includes('data-i18n-aria-label="chat.talkToLexaBtn"'));
assert("talk-to-lexa button is an accessible toggle", html.includes('id="talk-to-lexa-btn" type="button" aria-pressed="false"') && html.includes('data-i18n-title="app.orbClickSpeak"') && html.includes("data-voice-entry-label"));
assert("composer voice buttons are accessible toggles", html.includes('id="tts-toggle" type="button" aria-pressed="false"') && html.includes('data-i18n-aria-label="chat.ttsToggleLabel"') && html.includes('id="mic-btn" type="button" aria-pressed="false" aria-busy="false"') && html.includes('data-i18n-title="chat.micStartTitle"'));
assert("non-native action controls activate on keyboard", src.includes("function _isKeyboardActionTarget") && src.includes('document.addEventListener("keydown"') && src.includes('e.key === "Enter"') && src.includes('e.key === " "') && src.includes("_safeDispatch(el, el.dataset, null)"));
assert("delegated action controls are auto-accessible", src.includes("function _setupActionAccessibility") && src.includes('root.querySelectorAll?.("[data-action]")') && src.includes('el.setAttribute("role", "button")') && src.includes('el.setAttribute("tabindex", "0")') && src.includes("new MutationObserver"));
assert("delegated action failures are contained", src.includes("function _safeDispatch") && src.includes('console.warn("[Action] Handler failed:"') && src.includes("Invalid data-params for runTool") && src.includes("JSON.parse(ds.params)"));
assert("i18n translates aria labels", i18nSrc.includes("[data-i18n-aria-label]") && i18nSrc.includes('el.setAttribute("aria-label", translated)'));
assert("German and English i18n dictionaries have matching non-empty keys", i18nDeKeys.length > 1000 && i18nDeKeys.length === i18nEnKeys.length && i18nKeyMismatches.length === 0 && emptyI18nValues.length === 0, [...i18nKeyMismatches, ...emptyI18nValues].join(", "));
assert("literal i18n references exist in German and English", missingI18nRefs.length === 0, missingI18nRefs.join(", "));
assert("all command descriptors are translated in German and English", commandNames.length >= 100 && missingCommandDescRefs.length === 0, missingCommandDescRefs.join(", "));
assert("screenshot analysis preflights provider readiness before critical vision call", src.includes("function visionStatusPayload") && src.includes("function visionIsReady") && src.includes("await window.lexa.visionStatus()") && src.includes('t("vision.providerRequiredChat")') && src.includes('t("vision.providerRequiredToast")') && src.includes('t("vision.analysisComplete")') && src.includes('t("vision.analysisFailed")') && !src.includes('"[Vision] " + result.data.analysis') && i18nDe.includes('"vision.providerRequiredChat"') && i18nEn.includes('"vision.providerRequiredToast"'));
assert("topbar icon buttons expose translated aria labels", html.includes('id="wakeword-indicator"') && html.includes('data-i18n-aria-label="nav.wakeWordTooltip"') && html.includes('id="notif-bell-btn"') && html.includes('data-i18n-aria-label="notifications.title"') && html.includes('data-i18n-aria-label="nav.memory"') && html.includes('data-i18n-aria-label="nav.settings"'));
assert("notification center dialog and close control are localized", html.includes('id="notif-center" role="dialog"') && html.includes('data-i18n-aria-label="notifications.title"') && html.includes('class="notif-center-close"') && html.includes('data-i18n-aria-label="common.close"'));
assert("notification center synchronizes expanded, hidden, and focus state", html.includes('id="notif-center" role="dialog"') && html.includes('aria-hidden="true"') && html.includes('id="notif-bell-btn"') && html.includes('aria-expanded="false"') && html.includes('aria-controls="notif-center"') && modalsSrc.includes("function ensureNotifCenterA11y") && modalsSrc.includes("function setNotifCenterOpen") && modalsSrc.includes('panel.setAttribute("aria-hidden", "false")') && modalsSrc.includes('btn.setAttribute("aria-expanded", "true")') && modalsSrc.includes('btn.setAttribute("aria-controls", "notif-center")') && modalsSrc.includes("trapFocusIn(panel, event)") && modalsSrc.includes("restoreFocus(_notifCenterRestoreFocusEl)") && modalsSrc.includes('panel.setAttribute("tabindex", "-1")'));
assert("notification center uses CSP-safe top-layer positioning classes", modalsSrc.includes("function positionNotifCenter") && modalsSrc.includes('classList.toggle("notif-center-compact", compact)') && modalsSrc.includes('classList.toggle("notif-center-short", shortViewport)') && !modalsSrc.includes(".style.setProperty") && !modalsSrc.includes("--notif-panel-left") && overridesCss.includes("#app > .notif-center") && overridesCss.includes("top: 76px") && overridesCss.includes("#app > .notif-center.notif-center-compact") && overridesCss.includes("z-index: 12010") && overridesCss.includes("#app > .toast-container") && overridesCss.includes("z-index: 14000"));
assert("hidden attach button is named for accessibility", html.includes('id="attach-btn"') && html.includes('data-i18n-aria-label="chat.attachFile"') && i18nDe.includes('"chat.attachFile"') && i18nEn.includes('"chat.attachFile"'));
assert("voice orb has visible keyboard focus styling", overridesCss.includes("#voice-orb-canvas:focus-visible") && overridesCss.includes("outline-offset: 6px") && overridesCss.includes(".talk-to-lexa-btn:focus-visible"));
assert("voice entry controls expose active pressed state and localized action labels", src.includes("function _updateOrbActionA11y") && src.includes('control.setAttribute("aria-pressed"') && src.includes('talkBtn.classList.toggle("listening", isActive)') && src.includes('"app.orbClickEnd"') && src.includes('"chat.endConversation"'));
assert("talk-to-lexa button render keeps structured localized label", chatSrc.includes("function renderTalkButton") && chatSrc.includes("data-voice-entry-label") && chatSrc.includes('data-i18n="') && chatSrc.includes("_updateOrbActionA11y(active)"));
assert("classic voice recording keeps orb pressed state in sync", chatSrc.includes("_updateOrbActionA11y(true)") && chatSrc.includes("_updateOrbActionA11y(false)"));
assert("orb click checks voice boundary before starting stable voice", src.includes("async function _primeOrbRealtimeBoundary") && src.includes("window.lexa?.voiceRealtimeStart") && src.includes("Ich nutze den stabilen Sprachweg:"));
assert("orb click uses an orb-only voice surface", src.includes("function _setOrbVoiceSurfaceActive") && src.includes("window.__lexaOrbVoiceActive = Boolean(active)") && src.includes("_setOrbVoiceSurfaceActive(true)") && src.includes("_setOrbVoiceSurfaceActive(false)") && chatSrc.includes("function voiceUsesOrbSurface") && chatSrc.includes("voiceHideStatusBar()"));
assert("orb realtime preflight avoids visible status chrome during orb flow", src.includes("const orbSurface = Boolean(window.__lexaOrbVoiceActive)") && src.includes('_updateOrbVoiceSurfaceStatus("processing")') && src.includes('_updateOrbVoiceSurfaceStatus("listening")') && src.includes("VoiceStatusBar.hide()"));
assert("orb click does not start classic recording after realtime starts", src.includes("function _voiceRealtimeStarted") && src.includes("_orbRealtimeVoiceActive = true") && src.includes("_updateOrbActionA11y(true)") && src.includes("if (realtimeStarted) return;"));
assert("orb click can stop an active realtime voice session", src.includes("async function stopOrbConversation") && src.includes("window.lexa?.voiceRealtimeStop") && src.includes("_orbRealtimeVoiceActive = false") && src.includes("_updateOrbActionA11y(false)"));
assert("orb status labels cascaded path without provider jargon", src.includes("function _voicePathLabel") && src.includes("return _voiceProcessingProviderLabel()"));
assert("wake word events update shared voice status bar", src.includes("function _voiceStatusBarEventUpdate") && src.includes("_voiceWakeProviderLabel()") && src.includes("_voiceConversationProviderLabel()"));
assert("wake word timeout gives visible command guidance", src.includes('case "wake_timeout"') && src.includes('"app.voiceWakeNoCommand"') && i18nDe.includes('"app.voiceWakeNoCommand"') && i18nEn.includes('"app.voiceWakeNoCommand"'));
assert("wake word status bar mirrors command response and hides speaking chrome", src.includes("_voiceProcessingProviderLabel()") && src.includes("provider: evt.tts_handled ? _voiceSpeechProviderLabel() : _voiceResponseProviderLabel()") && src.includes("_voiceSpeakingResponseLabel()") && src.includes('state: "speaking"') && src.includes('safeState === "speaking"') && src.includes("VoiceStatusBar.hide()"));
assert("chat TTS shares the main orb speaking state", src.includes("window.setOrbConversationState = _setOrbConversationState") && src.includes("orbContainer.dataset.convState = safeState") && chatSrc.includes('voiceSetOrbConversationState("speaking")') && chatSrc.includes("voiceSetOrbConversationState(null)"));
assert("voice status bar markup carries the styling class", html.includes('id="voice-status-bar" class="voice-status-bar hidden"') && html.includes('class="voice-status-left"') && html.includes('class="voice-status-center"') && html.includes('class="voice-status-right"'));
assert("voice status bar announces atomic live state", html.includes('role="status"') && html.includes('aria-live="polite"') && html.includes('aria-atomic="true"') && src.includes("_refreshA11yLabel()") && src.includes('setAttribute("aria-label"'));
assert("voice status bar canvas has stable dimensions", html.includes('id="voice-level-meter" width="96" height="24"') && voiceCss.includes("#voice-level-meter") && voiceCss.includes("width: 72px"));
assert("voice level meter is hidden from assistive tech", html.includes('id="voice-level-meter" width="96" height="24" aria-hidden="true"'));
assert("voice status bar uses product-style compact chrome", voiceCss.includes("rgba(10, 10, 17, 0.82)") && voiceCss.includes("border-radius: 10px") && voiceCss.includes("font-style: normal"));
assert("voice status bar is centered as an overlay", voiceCss.includes("position: fixed") && voiceCss.includes("left: 50%") && voiceCss.includes("transform: translateX(-50%)"));
assert("voice status bar stays fixed after app layering overrides", overridesCss.includes("#voice-status-bar {\n  position: fixed") && overridesCss.includes("z-index: 12000") && !overridesCss.includes("#app > .main-layout,\n#voice-status-bar"));
assert("voice status labels avoid emoji debug copy", src.includes('listening: _voiceText("app.voiceStateListening"') && src.includes('processing: _voiceText("app.voiceStateProcessing"') && src.includes('speaking: _voiceText("app.voiceStateSpeaking"') && !src.includes('listening: "\\uD83C\\uDFA4'));
assert("voice status visible copy uses i18n keys", src.includes("function _voiceText") && src.includes('t(key, values)') && src.includes('"app.voiceRealtimeReady"') && src.includes('"app.voiceClassicFallback"') && src.includes('"app.voiceProviderProcessing"') && i18nDe.includes('"app.voiceClassicFallback"') && i18nEn.includes('"app.voiceClassicFallback"'));
assert("voice status bar clips long visible text with inspectable titles", src.includes("function _voiceStatusTextClip") && src.includes("function _voiceStatusSetText") && src.includes('el.title = text') && src.includes('[truncated]'));
assert("voice status bar normalizes unknown states", src.includes("function _voiceStatusState") && src.includes('"listening", "processing", "speaking", "error", "bargein"') && src.includes("const safeState = _voiceStatusState(state)"));
assert("voice status transcript/provider use bounded setters", src.includes("_voiceStatusSetText(this._transcript, text, 140)") && src.includes("_voiceStatusSetText(this._provider, name, 48)") && src.includes("Math.round(Number(ms))"));
assert("voice level meter avoids black debug blocks", src.includes("Math.max(0, Math.min(1, Number(vol) || 0))") && src.includes("drawRoundRect(0.5, 5.5") && src.includes("clearVolume()") && src.includes("volumeOnly") && !src.includes('ctx.fillStyle = "rgba(255,255,255,0.03)"'));
assert("compact orb remains legible in active chat", overridesCss.includes("clamp(128px, 8vw, 164px)") && overridesCss.includes("drop-shadow(0 0 18px"));
assert("orb renderer keeps a dark particle-first Lexa material", orb3dSrc.includes("0x2a144a") && orb3dSrc.includes("0x05010a") && orb3dSrc.includes("0x3a2266") && orb3dSrc.includes("0x00f0ff") && orb3dSrc.includes("0xff00a0"));
assert("orb renderer avoids debug wireframe or white-gloss form changes", !orb3dSrc.includes("WireframeGeometry") && !orb3dSrc.includes("DirectionalLight") && !orb3dSrc.includes("emissiveIntensity") && orb3dSrc.includes("computeVertexNormals()"));
assert("orb renderer avoids over-dense loop stutter", orb3dSrc.includes("detail: 12") && orb3dSrc.includes("this.options.detail = 4") && orb3dSrc.includes("new THREE.BufferGeometry()") && orb3dSrc.includes("const numPoints = 1800") && orb3dSrc.includes("geometryUpdateMs") && orb3dSrc.includes("colorUpdateMs") && orb3dSrc.includes("normalUpdateMs"));
assert("orb renderer has a frame-spike performance fallback", orb3dSrc.includes("this._perfMode") && orb3dSrc.includes("frameDelta > 115") && orb3dSrc.includes("this._perfMode = Math.min(2") && orb3dSrc.includes("geometryInterval") && orb3dSrc.includes("normalInterval"));
assert("orb orientation drifts organically instead of looping like a video", orb3dSrc.includes("_applyOrganicOrientation") && orb3dSrc.includes("_organicDrift") && !orb3dSrc.includes("rotationSpeedY") && !orb3dSrc.includes("rotationSpeedX") && !orb3dSrc.includes("this.group.rotation.z = convState"));
assert("speaking orb has organic movement beyond glow", orb3dSrc.includes("stateSyntheticVolume") && orb3dSrc.includes('convState === "speaking"') && orb3dSrc.includes("this._organicPulse(now, 1.45") && orb3dSrc.includes("this.group.rotation.z") && overridesCss.includes("#voice-orb-canvas.conv-speaking") && overridesCss.includes("animation: none"));
assert("listening orb visibly changes shape without looping canvas keyframes", orb3dSrc.includes("stateShapeWarp") && orb3dSrc.includes("listenPulse") && orb3dSrc.includes("stateSyntheticVolume = 0.08 + listenPulse") && orb3dSrc.includes('convState === "listening"') && orb3dSrc.includes("this._organicPulse(now, 0.92") && overridesCss.includes("#voice-orb-canvas.conv-listening") && overridesCss.includes("animation: none"));
assert("chat input can shrink without overlapping action buttons", overridesCss.includes("#chat-input") && overridesCss.includes("min-width: 0") && overridesCss.includes(".sleek-actions-right") && overridesCss.includes("flex-shrink: 0"));
assert("mobile top nav hides low-priority text before overflow", overridesCss.includes(".top-nav-pill .nav-time") && overridesCss.includes("display: none") && overridesCss.includes("max-width: 86px"));
assert("mobile chat input keeps stable icon button dimensions", overridesCss.includes(".send-btn.sleek-icon-btn") && overridesCss.includes("width: 34px") && overridesCss.includes("height: 34px"));
assert("open chat layout reduces vertical dead space", overridesCss.includes(".chat-container:has(.voice-orb-container.compact) .chat-messages") && overridesCss.includes("padding-top: 10px") && overridesCss.includes("padding: 18px 0 8px"));
assert("chat input CSS is textarea-ready", overridesCss.includes("max-height: 160px") && overridesCss.includes("resize: none") && overridesCss.includes("overflow-y: hidden") && overridesCss.includes("align-items: flex-end"));
assert("chat composer only sticks in open transcript mode", overridesCss.includes(".chat-input-area.sleek-input-area") && overridesCss.includes("position: relative") && overridesCss.includes(".chat-container:has(.voice-orb-container.compact) .chat-input-area.sleek-input-area") && overridesCss.includes("position: sticky"));
assert("chat surface matches requested animated composer shell", html.includes("chat-container active animated-ai-chat") && html.includes('data-i18n="chat.heroTitle"') && html.includes('id="attach-btn" class="sleek-icon-btn attach-btn"') && html.includes('class="send-btn-label"') && overridesCss.includes(".animated-ai-chat .sleek-pill") && overridesCss.includes('grid-template-areas:') && overridesCss.includes('"input input input"') && overridesCss.includes('"attach spacer actions"') && overridesCss.includes(".animated-ai-chat #send-btn"));
assert("chat home keeps workflow launchers as compact icons below the composer", overridesCss.includes(".animated-ai-chat .conversation-starters") && overridesCss.includes("order: 21") && overridesCss.includes("grid-template-columns: repeat(4, 40px)") && overridesCss.includes(".animated-ai-chat .starter-content") && overridesCss.includes("display: none") && overridesCss.includes(".animated-ai-chat .composer-command-btn") && overridesCss.includes("display: none") && overridesCss.includes(".animated-ai-chat #send-btn .send-btn-label") && overridesCss.includes("display: none"));
assert("chat home starter rail uses simple assistant modes before advanced UI workflows", chatSrc.includes('const starterCommandIds = ["workspace", "research", "think", "os"]') && i18nDe.includes('"composer.workspace.label": "Schreiben"') && i18nDe.includes('"composer.os.label": "Privates"') && i18nEn.includes('"composer.workspace.label": "Write"') && i18nEn.includes('"composer.os.label": "Personal"'));
assert("chat home orb is large enough to be the primary visual signal", overridesCss.includes(".animated-ai-chat .voice-orb-container:not(.compact) #voice-orb-canvas") && overridesCss.includes("width: clamp(188px, 14vw, 232px)") && overridesCss.includes("height: clamp(188px, 14vw, 232px)") && overridesCss.includes("width: 152px") && overridesCss.includes("height: 152px"));
assert("conversation starters use inline SVG command icons instead of emoji text", chatComposerSrc.includes("function composerCommandIconSvg") && chatSrc.includes("iconEl.innerHTML = composerCommandIconSvg(command.icon") && !chatSrc.includes("iconEl.textContent = s.icon"));
assert("conversation starters are native named command buttons", chatSrc.includes('card.type = "button"') && chatSrc.includes('card.setAttribute("aria-label", `${label}: ${desc}. ${hint}`)') && chatSrc.includes("selectComposerCommand(command.id)"));
assert("conversation sidebar rows are keyboard accessible", chatSrc.includes("function bindKeyboardAction") && chatSrc.includes('el.setAttribute("role", "button")') && chatSrc.includes('el.setAttribute("tabindex", "0")') && chatHistoryUiSrc.includes('item.setAttribute("aria-current"') && chatHistoryUiSrc.includes("bindKeyboardAction(item, () => switchConversation(conversation.id)") && chatHistoryUiSrc.includes("chat.openConversationLabel"));
assert("conversation action buttons are named and focus-visible", chatHistoryUiSrc.includes('exportBtn.type = "button"') && chatHistoryUiSrc.includes("chat.exportConversationLabel") && chatHistoryUiSrc.includes('delBtn.type = "button"') && chatHistoryUiSrc.includes("chat.deleteConversationLabel") && overridesCss.includes(".conv-item:focus-visible") && overridesCss.includes(".conv-item:focus-within .conv-actions"));
assert("conversation sidebar surfaces agent runs needing attention", chatSrc.includes("function agentRunAttentionForConversation") && chatSrc.includes("function renderAgentAttentionPanel") && chatSrc.includes("renderAgentAttentionPanel(container, convList)") && chatSrc.includes('panel.className = "agent-attention-panel"') && chatSrc.includes('btn.className = "agent-attention-item"') && chatSrc.includes("btn.addEventListener(\"click\", () => switchConversation(item.convId))") && overridesCss.includes(".agent-attention-panel") && overridesCss.includes(".agent-attention-item:focus-visible") && i18nDe.includes('"chat.agentAttentionTitle"') && i18nEn.includes('"chat.agentAttentionOpenLabel"'));
assert("conversation sidebar can filter chats needing agent attention", html.includes('id="agent-attention-filter-btn"') && html.includes('data-action="toggleAgentAttentionFilter"') && html.includes('aria-pressed="false"') && chatSrc.includes("function agentRunAttentionListForConversations") && chatSrc.includes("function updateAgentAttentionFilterButton") && chatSrc.includes("function toggleAgentAttentionFilter") && chatSrc.includes('LexaState.set("conversationAttentionOnly", next)') && chatSrc.includes("if (attentionOnly && attentionList.length === 0)") && chatSrc.includes('LexaState.set("conversationAttentionOnly", false)') && chatSrc.includes("const visibleConversations = attentionOnly ? convList.filter") && chatHistoryUiSrc.includes('item.className = "conv-item" + (isActive ? " active" : "") + (attention ? " needs-agent-attention" : "")') && chatHistoryUiSrc.includes('badge.className = "conv-agent-attention-badge"') && overridesCss.includes(".agent-attention-filter-btn[aria-pressed=\"true\"]") && overridesCss.includes(".agent-attention-filter-note") && overridesCss.includes(".conv-agent-attention-badge") && i18nDe.includes('"chat.agentAttentionFilterLabel"') && i18nEn.includes('"chat.noAgentAttentionConversations"'));
assert("conversation sidebar can mark agent attention resolved locally", chatSrc.includes("function agentRunAttentionResolvedCacheKey") && chatSrc.includes("function resolveAgentAttentionForConversation") && chatSrc.includes("saveAgentRunAttentionResolvedKeys(convId, resolved)") && chatSrc.includes('showToast(t("chat.agentAttentionResolved")') && chatSrc.includes('resolveBtn.className = "agent-attention-resolve-btn"') && chatHistoryUiSrc.includes('resolveBtn.className = "conv-action-btn conv-agent-resolve-btn"') && chatSrc.includes("resolveAgentAttentionForConversation(item.convId, item.title)") && chatHistoryUiSrc.includes("resolveAgentAttentionForConversation(conversation.id, conversation.title)") && overridesCss.includes(".agent-attention-resolve-btn") && overridesCss.includes(".conv-agent-resolve-btn:focus-visible") && i18nDe.includes('"chat.agentAttentionResolveLabel"') && i18nEn.includes('"chat.agentAttentionResolved"'));
assert("conversation sidebar shows recently resolved agent attention", chatSrc.includes("function agentRunAttentionResolvedHistory") && chatSrc.includes("function agentRunAttentionResolvedHistoryForConversations") && chatSrc.includes("function recordAgentAttentionResolution") && chatSrc.includes("function restoreAgentAttentionHistoryItem") && chatSrc.includes("function renderAgentResolvedHistoryPanel") && chatSrc.includes("renderAgentResolvedHistoryPanel(container, convList)") && chatSrc.includes('panel.className = "agent-resolved-panel"') && chatSrc.includes('restoreBtn.className = "agent-resolved-restore-btn"') && chatSrc.includes("restoreAgentAttentionHistoryItem(item)") && overridesCss.includes(".agent-resolved-panel") && overridesCss.includes(".agent-resolved-restore-btn:focus-visible") && i18nDe.includes('"chat.agentResolvedTitle"') && i18nEn.includes('"chat.agentResolvedRestoreLabel"'));
assert("conversation resolved attention history prunes stale local entries", chatSrc.includes("function agentRunAttentionResolvedHistoryLimit") && chatSrc.includes("function agentRunAttentionResolvedHistoryMaxAgeMs") && chatSrc.includes("function normalizeAgentRunAttentionResolvedHistoryItems") && chatSrc.includes("function agentRunAttentionResolvedHistoryItemHasEvidence") && chatSrc.includes("function pruneAgentRunAttentionResolvedHistoryItems") && chatSrc.includes("now - item.resolved_at > maxAgeMs") && chatSrc.includes("agentRunAttentionResolvedHistoryItemHasEvidence(item)") && chatSrc.includes("JSON.stringify(pruned)") && chatSrc.includes("saveAgentRunAttentionResolvedHistory(pruned)"));
assert("conversation header summarizes agent attention state", html.includes('id="agent-attention-summary"') && html.includes('role="status"') && chatSrc.includes("function updateAgentAttentionHeaderSummary") && chatSrc.includes('document.getElementById("agent-attention-summary")') && chatSrc.includes("agentRunAttentionResolvedHistoryForConversations(convList).length") && chatSrc.includes('open.className = "agent-attention-summary-chip open"') && chatSrc.includes('resolved.className = "agent-attention-summary-chip resolved"') && chatSrc.includes('clear.className = "agent-attention-summary-chip clear"') && chatSrc.includes("updateAgentAttentionHeaderSummary(attentionList, convList)") && overridesCss.includes(".agent-attention-summary-chip.open") && overridesCss.includes(".agent-attention-summary-chip.resolved") && overridesCss.includes(".agent-attention-summary-chip.clear") && i18nDe.includes('"chat.agentAttentionHeaderClear"') && i18nEn.includes('"chat.agentAttentionHeaderClearLabel"'));
assert("mobile conversation attention chrome avoids sidebar overflow", overridesCss.includes("@media (max-width: 560px)") && overridesCss.includes(".conversations-section .sidebar-label") && overridesCss.includes("flex-wrap: wrap") && overridesCss.includes(".agent-attention-summary {\n    order: 2") && overridesCss.includes("flex: 1 0 100%") && overridesCss.includes("max-width: 100%") && overridesCss.includes(".agent-attention-summary-chip {\n    max-width: calc(50% - 2px)") && overridesCss.includes(".agent-attention-count,\n  .agent-resolved-count") && overridesCss.includes("overflow-wrap: anywhere"));
assert("conversation starter cards have calmer product styling", overridesCss.includes(".starter-icon svg") && overridesCss.includes("min-height: 58px") && overridesCss.includes("box-shadow: none") && overridesCss.includes("letter-spacing: 0"));
assert("assistant answers can hand off into workspace drafts", chatMessageActionsSrc.includes("function workspaceDraftPromptFromText") && chatMessageActionsControllerSrc.includes("function startWorkspaceDraftFromMessage") && chatMessageActionsControllerSrc.includes("function createWorkspaceHandoffButton") && chatMessageActionsControllerSrc.includes("msg-workspace-btn") && chatMessageActionsSrc.includes("Source clipped for chat handoff") && chatMessageActionsControllerSrc.includes('if (!LexaState.get("backendOnline")) { showToast(t("common.backendOffline"), "error"); return; }') && chatSrc.includes("workspaceBtn.disabled = true") && chatMessageActionsControllerSrc.includes('sendAgentMessage(prompt, { displayText: t("chat.workspaceHandoffUserMessage") })') && i18nDe.includes('"chat.workspaceHandoffTooltip"') && i18nEn.includes('"chat.workspaceHandoffTooltip"') && i18nDe.includes('"chat.workspaceHandoffStarted"') && i18nEn.includes('"chat.workspaceHandoffStarted"') && i18nDe.includes('"chat.workspaceHandoffUserMessage"') && i18nEn.includes('"chat.workspaceHandoffUserMessage"'));
assert("workspace handoff prevents duplicate starts while busy", chatMessageActionsControllerSrc.includes("if (btn?.disabled) return") && chatMessageActionsControllerSrc.includes('btn.setAttribute("aria-busy", "true")') && chatMessageActionsControllerSrc.includes("try {\n    await sendAgentMessage(prompt, { displayText: t(\"chat.workspaceHandoffUserMessage\") });\n  } finally") && chatMessageActionsControllerSrc.includes("btn.disabled = false") && chatMessageActionsControllerSrc.includes('btn.removeAttribute("aria-busy")'));
assert("assistant answers can be reused as composer context", chatMessageActionsSrc.includes("function continuePromptFromText") && chatMessageActionsControllerSrc.includes("function startContinueFromMessage") && chatMessageActionsControllerSrc.includes("function createContinueFromMessageButton") && chatMessageActionsControllerSrc.includes("msg-continue-btn") && chatMessageActionsSrc.includes("nextRequestHeadroom") && chatMessageActionsSrc.includes("chat.continueFromAnswerClipMarker") && chatMessageActionsControllerSrc.includes('localStorage.setItem("lexa-chat-draft", prompt.text)') && chatMessageActionsControllerSrc.includes("chatInput.setSelectionRange(prompt.cursorStart, prompt.cursorStart)") && chatMessageActionsControllerSrc.includes('flashIconButton(btn, "\\u2713", "\\u21AA", 1500, t("chat.continueFromAnswerStarted"))') && chatCss.includes(".msg-continue-btn:hover") && i18nDe.includes('"chat.continueFromAnswerTooltip"') && i18nEn.includes('"chat.continueFromAnswerTooltip"') && i18nDe.includes('"chat.continueFromAnswerStarted"') && i18nEn.includes('"chat.continueFromAnswerStarted"') && i18nDe.includes('"chat.continueFromAnswerPrefix"') && i18nEn.includes('"chat.continueFromAnswerPrefix"') && i18nDe.includes('"chat.continueFromAnswerClipMarker"') && i18nEn.includes('"chat.continueFromAnswerClipMarker"'));
assert("assistant answers can be verified with sources", chatMessageActionsSrc.includes("function verifyAnswerPromptFromText") && chatMessageActionsControllerSrc.includes("function startVerifyAnswerFromMessage") && chatMessageActionsControllerSrc.includes("function createVerifyAnswerButton") && chatMessageActionsControllerSrc.includes("msg-verify-btn") && chatMessageActionsSrc.includes('LEXA_COMPOSER_COMMANDS.find((command) => command.id === "research")') && chatMessageActionsSrc.includes("Extract checkable claims") && chatMessageActionsControllerSrc.includes('if (!LexaState.get("backendOnline")) { showToast(t("common.backendOffline"), "error"); return; }') && chatMessageActionsControllerSrc.includes('sendAgentMessage(prompt, { displayText: t("chat.verifyAnswerUserMessage") })') && chatMessageActionsControllerSrc.includes('flashIconButton(btn, "\\u2713", "?", 1800, t("chat.verifyAnswerStarted"))') && chatCss.includes(".msg-verify-btn:hover") && i18nDe.includes('"chat.verifyAnswerTooltip"') && i18nEn.includes('"chat.verifyAnswerTooltip"') && i18nDe.includes('"chat.verifyAnswerStarted"') && i18nEn.includes('"chat.verifyAnswerStarted"') && i18nDe.includes('"chat.verifyAnswerClipMarker"') && i18nEn.includes('"chat.verifyAnswerClipMarker"'));
assert("assistant answers can export portable markdown", chatExportSrc.includes("function messageExportMarkdownFromText") && chatExportSrc.includes("function messageExportFilename") && chatMessageActionsControllerSrc.includes("function exportMessageMarkdown") && chatMessageActionsControllerSrc.includes("function createMessageExportButton") && chatMessageActionsControllerSrc.includes("msg-export-btn") && chatMessageActionsControllerSrc.includes("text/markdown;charset=utf-8") && chatMessageActionsControllerSrc.includes("getMessagePersistText(btn?.closest(\".message\"))") && chatMessageActionsControllerSrc.includes("btn.disabled = false") && i18nDe.includes('"chat.exportMessageTooltip"') && i18nEn.includes('"chat.exportMessageTooltip"') && i18nDe.includes('"chat.messageExported"') && i18nEn.includes('"chat.messageExported"'));
assert("loaded chat messages put copy and high-reuse answer actions before secondary actions", /header\.appendChild\(timeSpan\);\s*header\.appendChild\(copyBtn\);\s*if \(!isUser\)/.test(chatSrc) && /header\.appendChild\(createContinueFromMessageButton\(\)\);\s*header\.appendChild\(createVerifyAnswerButton\(\)\);\s*header\.appendChild\(createMessageExportButton\(\)\);/.test(chatSrc) && chatSrc.includes("const moreActions = [thumbsBtn, createWorkspaceHandoffButton()]") && chatSrc.includes("header.appendChild(createMessageActionOverflowMenu(moreActions))") && /header\.appendChild\(editBtn\);\s*\/\/ Delete button for user messages/.test(chatSrc));
assert("streamed assistant answers expose full answer action set after completion", chatSrc.includes("copyBtn.disabled = true") && chatSrc.includes("memoryBtn.disabled = true") && chatSrc.includes("const workspaceBtn = createWorkspaceHandoffButton();\n  workspaceBtn.disabled = true") && chatSrc.includes("const continueBtn = createContinueFromMessageButton(true)") && chatSrc.includes("const verifyBtn = createVerifyAnswerButton(true)") && chatSrc.includes("const exportBtn = createMessageExportButton(true)") && chatSrc.includes("regenBtn.disabled = true") && chatSrc.includes("header.appendChild(createMessageActionOverflowMenu([memoryBtn, workspaceBtn, regenBtn]))") && chatSrc.includes("if (getMessagePersistText(msgEl))") && chatSrc.includes("verifyBtn.disabled = false;\n      exportBtn.disabled = false;\n      regenBtn.disabled = false;"));
assert("assistant markdown export prevents duplicate starts and reports failures", chatMessageActionsControllerSrc.includes("if (btn?.disabled) return") && chatMessageActionsControllerSrc.includes('btn.setAttribute("aria-busy", "true")') && chatMessageActionsControllerSrc.includes('showToast(t("toast.exportError")') && chatMessageActionsControllerSrc.includes("console.warn(\"[Chat] Message markdown export failed:\"") && chatMessageActionsControllerSrc.includes("URL.revokeObjectURL(url)") && chatMessageActionsControllerSrc.includes("finally {\n    if (link) link.remove();\n  }") && chatMessageActionsControllerSrc.includes("btn.disabled = false") && chatMessageActionsControllerSrc.includes('btn.removeAttribute("aria-busy")'));
assert("assistant memory save prevents duplicate starts and reports failures", chatMessageActionsControllerSrc.includes("async function saveMessageAsMemory") && chatMessageActionsControllerSrc.includes("getMessagePersistText(msg)") && chatMessageActionsControllerSrc.includes('if (!LexaState.get("backendOnline")) { showToast(t("common.backendOffline"), "error"); return; }') && chatMessageActionsControllerSrc.includes('await window.lexa.memoryAdd(t("chat.helpfulAnswer", {snippet}), "learned", 5)') && chatMessageActionsControllerSrc.includes("console.warn(\"[Chat] Save message as memory failed:\"") && chatMessageActionsControllerSrc.includes('showToast(t("toast.executionError"), "error", 2200)') && chatSrc.includes('thumbsBtn.addEventListener("click", () => saveMessageAsMemory(thumbsBtn, msg))') && chatMessageActionsControllerSrc.includes('btn.setAttribute("aria-label", t("toast.savedAsMemory"))') && chatMessageActionsControllerSrc.includes('btn.removeAttribute("aria-busy")'));
assert("agent summaries expose copy, memory, continue, and verify actions when complete", chatSrc.includes('nameSpan.textContent = t("chat.systemNameLexa")') && !chatSrc.includes('nameSpan.textContent = t("chat.systemNameLexa") + " Agent"') && chatSrc.includes('memoryBtn.className = "msg-thumbs-btn"') && chatSrc.includes('memoryBtn.disabled = true') && chatSrc.includes('memoryBtn.addEventListener("click", () => saveMessageAsMemory(memoryBtn, msgEl))') && chatSrc.includes("const continueBtn = createContinueFromMessageButton(true)") && chatSrc.includes("const verifyBtn = createVerifyAnswerButton(true)") && chatSrc.includes('header.appendChild(copyBtn)') && chatSrc.includes('header.appendChild(continueBtn)') && chatSrc.includes('header.appendChild(verifyBtn)') && chatSrc.includes("header.appendChild(createMessageActionOverflowMenu([memoryBtn, workspaceBtn]))") && chatSrc.includes("copyBtn.disabled = false;\n            memoryBtn.disabled = false;") && chatSrc.includes("continueBtn.disabled = false;\n            verifyBtn.disabled = false;") && chatSrc.includes("copyBtn.disabled = false;\n    memoryBtn.disabled = false;"));
assert("agent runs expose visible busy status and live step semantics", chatSrc.includes('msgEl.setAttribute("aria-busy", "true")') && chatSrc.includes('msgEl.removeAttribute("aria-busy")') && chatSrc.includes('summaryEl.className = "agent-summary agent-status"') && chatSrc.includes('summaryEl.setAttribute("role", "status")') && chatSrc.includes('summaryEl.setAttribute("aria-live", "polite")') && chatSrc.includes('summaryEl.textContent = t("chat.agentStarting")') && chatSrc.includes('summaryEl.textContent = t("chat.agentWorking")') && chatSrc.includes('summaryEl.textContent = t("chat.agentCompleted")') && chatSrc.includes('stepsContainer.setAttribute("role", "list")') && chatSrc.includes('stepsContainer.setAttribute("aria-label", t("chat.agentStepsLabel"))') && chatSrc.includes('stepEl.setAttribute("role", "listitem")') && overridesCss.includes('.agent-message[aria-busy="true"] .agent-badge') && overridesCss.includes(".agent-steps:empty") && overridesCss.includes(".agent-summary.agent-status") && i18nDe.includes('"chat.agentStarting"') && i18nEn.includes('"chat.agentStarting"') && i18nDe.includes('"chat.agentStepsLabel"') && i18nEn.includes('"chat.agentStepsLabel"'));
assert("agent step labels are human-readable while preserving technical detail off the visible surface", chatSrc.includes("function agentStepDisplayLabel") && chatSrc.includes("function agentStepTechnicalLabel") && chatSrc.includes("function agentStepActionLabel") && chatSrc.includes('const commandKey = `cmd.desc.${name}`') && chatSrc.includes('name.startsWith("personal_os_")') && chatSrc.includes('name.startsWith("web_")') && chatSrc.includes('label.textContent = readableLabel') && chatSrc.includes("stepEl.dataset.technicalLabel = technicalLabel") && chatSrc.includes("stepEl.title = readableLabel") && chatSrc.includes('stepEl.setAttribute("aria-label", readableLabel)') && !chatSrc.includes('stepEl.setAttribute("aria-label", `${readableLabel}. ${technicalLabel}`)') && i18nDe.includes('"chat.agentStepPersonalOs"') && i18nEn.includes('"chat.agentStepPersonalOs"') && i18nDe.includes('"chat.agentStepWithDetail"') && i18nEn.includes('"chat.agentStepWithDetail"'));
assert("agent steps expose compact outcome badges without technical aria clutter", chatSrc.includes("function agentStepOutcomeKind") && chatSrc.includes("function agentStepOutcomeLabel") && chatSrc.includes("function renderAgentStepOutcome") && chatSrc.includes('badge.className = `agent-step-outcome ${kind}`') && chatSrc.includes("renderAgentStepOutcome(stepEl, step)") && chatSrc.includes('stepEl.setAttribute("aria-label", `${visibleLabel}. ${badge.textContent}`)') && !chatSrc.includes('stepEl.setAttribute("aria-label", `${visibleLabel}. ${badge.textContent}. ${technicalLabel}`)') && overridesCss.includes(".agent-step-outcome") && overridesCss.includes(".agent-step-outcome.found") && overridesCss.includes(".agent-step-outcome.changed") && overridesCss.includes(".agent-step-outcome.blocked") && overridesCss.includes(".agent-step-outcome.failed") && i18nDe.includes('"chat.agentOutcomeFound"') && i18nEn.includes('"chat.agentOutcomeFound"') && i18nDe.includes('"chat.agentOutcomeChanged"') && i18nEn.includes('"chat.agentOutcomeChanged"'));
assert("agent runs expose aggregate outcome summary chips", chatSrc.includes("function agentRunOutcomeCounts") && chatSrc.includes("function recordAgentStepOutcome") && chatSrc.includes("function renderAgentOutcomeSummary") && chatSrc.includes('outcomeSummaryEl.className = "agent-outcome-summary"') && chatSrc.includes("recordAgentStepOutcome(step, agentOutcomeCounts, agentStepOutcomes)") && chatSrc.includes("renderAgentOutcomeSummary(outcomeSummaryEl, agentOutcomeCounts)") && chatSrc.includes("const finalOutcomeCounts = Array.isArray(run.steps) && run.steps.length") && chatSrc.includes("renderAgentOutcomeSummary(outcomeSummaryEl, finalOutcomeCounts)") && overridesCss.includes(".agent-outcome-summary") && overridesCss.includes(".agent-outcome-chip.found") && overridesCss.includes(".agent-outcome-chip.failed") && i18nDe.includes('"chat.agentOutcomeSummaryLabel"') && i18nEn.includes('"chat.agentOutcomeSummaryLabel"'));
assert("agent runs expose structured completion panel", chatSrc.includes("function renderAgentCompletionPanel") && chatSrc.includes('completionEl.className = "agent-completion-panel"') && chatSrc.includes('completionEl.setAttribute("role", "group")') && chatSrc.includes("renderAgentCompletionPanel(completionEl, finalOutcomeCounts") && chatSrc.includes('agent-completion-grid') && chatSrc.includes('agent-completion-item') && overridesCss.includes(".agent-completion-panel") && overridesCss.includes(".agent-completion-panel.failed") && overridesCss.includes(".agent-completion-grid") && i18nDe.includes('"chat.agentCompletionNeedsYou"') && i18nEn.includes('"chat.agentCompletionNextFailed"'));
assert("agent chat surface uses polished final stylesheet", premiumCss.includes("/* Agent chat surface polish */") && premiumCss.includes(".agent-message .msg-action-icon") && premiumCss.includes(".agent-summary:not(.agent-status)") && premiumCss.includes(".agent-step.running .agent-step-icon") && premiumCss.includes(".agent-completion-state::before") && premiumCss.includes(".agent-completion-item") && premiumCss.includes(".agent-stop-btn.is-complete"));
assert("chat design system keeps transcript actions clean and legible", premiumCss.includes("/* Chat design system pass */") && premiumCss.includes(".message .msg-action-icon") && premiumCss.includes("width: 20px") && premiumCss.includes(".message .msg-copy-btn:hover") && premiumCss.includes("border-radius: 999px") && premiumCss.includes(".system-message:not(.agent-message) .msg-text") && premiumCss.includes(".user-message .msg-text") && premiumCss.includes(".message .msg-more-menu") && premiumCss.includes("min-width: 210px") && premiumCss.includes(".message .msg-more-menu .msg-action-btn"));
assert("agent completion panel can draft a continuation prompt", chatSrc.includes("function agentCompletionContinuePrompt") && chatSrc.includes("function startAgentCompletionContinue") && chatSrc.includes("agentCompletionContinuePrompt(run, finalOutcomeCounts") && chatSrc.includes('continueButton.className = "agent-completion-continue-btn"') && chatSrc.includes("continueButton._lexaAgentContinuePrompt = options.continuePrompt.text") && chatSrc.includes("localStorage.setItem(\"lexa-chat-draft\", prompt)") && chatSrc.includes("chatInput.setSelectionRange(cursorStart, cursorStart)") && overridesCss.includes(".agent-completion-continue-btn") && i18nDe.includes('"chat.agentCompletionContinueButton"') && i18nEn.includes('"chat.agentCompletionContinuePromptIntro"'));
assert("agent completion panel can mark attention resolved", chatSrc.includes("function startAgentCompletionResolve") && chatSrc.includes("function isAgentCompletionAttentionResolved") && chatSrc.includes("agentCompletionAttentionKeyFromText") && chatSrc.includes('resolveButton.className = "agent-completion-resolve-btn"') && chatSrc.includes('resolveButton.addEventListener("click", () => startAgentCompletionResolve(resolveButton))') && chatSrc.includes("markAgentCompletionResolveButtonDone(resolveButton)") && chatSrc.includes("saveAgentRunAttentionResolvedKeys(convId, resolved)") && chatSrc.includes("renderConversationList()") && overridesCss.includes(".agent-completion-resolve-btn") && overridesCss.includes(".agent-completion-resolve-btn.is-resolved") && i18nDe.includes('"chat.agentCompletionResolveButton"') && i18nEn.includes('"chat.agentCompletionResolveEmpty"'));
assert("agent completion panel can undo resolved attention", chatSrc.includes("function undoAgentCompletionResolve") && chatSrc.includes("function markAgentCompletionResolveButtonOpen") && chatSrc.includes('btn.dataset.resolved = "true"') && chatSrc.includes('btn.dataset.resolved = "false"') && chatSrc.includes('if (btn?.dataset?.resolved === "true") return undoAgentCompletionResolve(btn)') && chatSrc.includes("resolved.delete(key)") && chatSrc.includes('showToast(t("chat.agentAttentionRestored")') && overridesCss.includes("border-color: rgba(251, 191, 36, 0.22)") && i18nDe.includes('"chat.agentCompletionResolveUndoButton"') && i18nEn.includes('"chat.agentAttentionRestored"'));
assert("assistant message actions provide immediate accepted feedback", chatMessageActionsControllerSrc.includes("function flashIconButton") && chatMessageActionsControllerSrc.includes("button._lexaIconTimer") && chatMessageActionsControllerSrc.includes('flashIconButton(btn, "\\u2713", "\\u2398", 1500, t("toast.clipboardCopied"))') && chatMessageActionsControllerSrc.includes('flashIconButton(btn, "\\u2713", "\\u25A3", 1800, t("chat.workspaceHandoffStarted"))') && chatMessageActionsControllerSrc.includes('flashIconButton(btn, "\\u2713", "\\u21E9", 1500, t("chat.messageExported"))'));
assert("assistant message action success feedback is accessible", chatMessageActionsControllerSrc.includes("button._lexaOriginalAriaLabel") && chatMessageActionsControllerSrc.includes("button._lexaOriginalTitle") && chatMessageActionsControllerSrc.includes("button._lexaOriginalText") && chatMessageActionsControllerSrc.includes("button.textContent = originalText") && chatMessageActionsControllerSrc.includes('button.setAttribute("aria-label", feedbackLabel)') && chatMessageActionsControllerSrc.includes("button.title = feedbackLabel") && chatMessageActionsControllerSrc.includes('button.setAttribute("aria-label", button._lexaOriginalAriaLabel)') && chatMessageActionsControllerSrc.includes('button.removeAttribute("aria-label")') && chatMessageActionsControllerSrc.includes('button.removeAttribute("title")'));
assert("assistant copy actions have a clipboard fallback", chatMessageActionsControllerSrc.includes("async function copyTextToClipboard") && chatMessageActionsControllerSrc.includes("navigator.clipboard") && chatMessageActionsControllerSrc.includes('document.execCommand("copy")') && chatMessageActionsControllerSrc.includes('textarea.setAttribute("readonly", "")') && chatMessageActionsControllerSrc.includes('textarea.className = "clipboard-copy-buffer"') && overridesCss.includes(".clipboard-copy-buffer") && chatMessageActionsControllerSrc.includes("textarea.remove()") && chatMessageActionsControllerSrc.includes("copyTextToClipboard(code).then") && chatMessageActionsControllerSrc.includes("copyTextToClipboard(text).then") && chatMessageActionsControllerSrc.includes('showToast(t("toast.copyFailed")'));
assert("assistant answer actions preserve raw markdown fidelity", chatSrc.includes("function setMessagePersistText") && chatSrc.includes("msg.dataset.persistText = source") && chatSrc.includes("setMessagePersistText(msg, text)") && chatSrc.includes("setMessagePersistText(msgEl, fullText || textEl.textContent)") && chatSrc.includes("setMessagePersistText(msgEl, run.summary)") && chatSrc.includes("const stored = msg.dataset?.persistText") && chatMessageActionsControllerSrc.includes("getMessagePersistText(allMsgs[j])"));
assert("agent run metadata persists without polluting backend messages", chatSrc.includes("function normalizeAgentRunMeta") && chatSrc.includes("function setMessageAgentRunMeta") && chatSrc.includes("function getMessageAgentRunMeta") && chatSrc.includes("function saveAgentRunMetaForConversation") && chatSrc.includes("function createAgentRunMetaResolver") && chatSrc.includes("function renderPersistedConversationMessages") && chatSrc.includes('messages.push(meta ? { text, type, meta } : { text, type })') && chatSrc.includes("const convId = LexaState.get(\"currentConversationId\")") && chatSrc.includes("saveAgentRunMetaForConversation(convId)") && chatSrc.includes("messages.push({ role, content: text })") && chatSrc.includes("addMessage(text, type, null, false, true, { agentRunMeta: meta })") && chatSrc.includes("renderPersistedAgentRunMeta(body, agentRunMeta, text)"));
assert("assistant message action row wraps and keeps stable icon targets", overridesCss.includes(".msg-header") && overridesCss.includes("flex-wrap: wrap") && overridesCss.includes("max-width: 100%") && overridesCss.includes(".msg-copy-btn,") && overridesCss.includes("flex: 0 0 24px") && overridesCss.includes("width: 24px") && overridesCss.includes("height: 24px") && overridesCss.includes("text-overflow: ellipsis"));
assert("assistant message actions are visible on keyboard focus", overridesCss.includes(".message:focus-within .msg-copy-btn") && overridesCss.includes(".msg-copy-btn:focus-visible") && overridesCss.includes(".msg-thumbs-btn:focus-visible") && overridesCss.includes(".msg-action-btn:focus-visible") && overridesCss.includes("outline-offset: 2px") && overridesCss.includes(".message:focus-within .msg-action-btn:disabled"));
assert("assistant message actions expose real hover and focus tooltips", overridesCss.includes(".msg-copy-btn::after") && overridesCss.includes("content: attr(aria-label)") && overridesCss.includes("bottom: calc(100% + 6px)") && overridesCss.includes(".msg-copy-btn:hover::after") && overridesCss.includes(".msg-action-btn:focus::after") && overridesCss.includes("pointer-events: none"));
assert("assistant secondary answer actions collapse into an accessible more menu on touch", chatMessageActionsControllerSrc.includes("function createMessageActionOverflowMenu") && chatMessageActionsControllerSrc.includes('trigger.setAttribute("aria-haspopup", "menu")') && chatMessageActionsControllerSrc.includes('trigger.setAttribute("aria-expanded", "false")') && chatMessageActionsControllerSrc.includes('menu.setAttribute("role", "menu")') && chatMessageActionsControllerSrc.includes('button.setAttribute("role", "menuitem")') && chatMessageActionsControllerSrc.includes("closeMessageActionMenus") && chatMessageActionsControllerSrc.includes('const actionButton = event.target?.closest?.("button")') && chatMessageActionsControllerSrc.includes("if (!actionButton || !menu.contains(actionButton)) return") && chatMessageActionsControllerSrc.includes("const rect = trigger.getBoundingClientRect()") && chatMessageActionsControllerSrc.includes("if (rect.width > 0 && rect.height > 0) trigger.focus()") && chatMessageActionsControllerSrc.includes('setIconButton(trigger, "\\u22EF", t("chat.moreActionsTooltip"))') && overridesCss.includes(".msg-more-actions,\n.msg-more-menu {\n  display: contents") && overridesCss.includes(".msg-more-btn {\n  display: none") && overridesCss.includes(".msg-more-actions.open .msg-more-menu") && overridesCss.includes(".msg-more-menu .msg-thumbs-btn::after") && i18nDe.includes('"chat.moreActionsTooltip"') && i18nEn.includes('"chat.moreActionsTooltip"'));
assert("assistant message actions stay visible and larger on touch pointers", overridesCss.includes("@media (hover: none), (pointer: coarse)") && overridesCss.includes("flex-basis: 32px") && overridesCss.includes("height: 32px") && overridesCss.includes("opacity: 0.78") && overridesCss.includes(".msg-copy-btn:disabled,\n  .msg-thumbs-btn:disabled,\n  .msg-action-btn:disabled"));
assert("narrow touch answer actions prioritize reuse actions before secondary actions", overridesCss.includes("@media (max-width: 420px) and (hover: none), (max-width: 420px) and (pointer: coarse)") && overridesCss.includes(".msg-name {\n    flex: 1 1 12ch") && overridesCss.includes(".msg-time {\n    order: 0;\n    margin-inline-end: auto") && overridesCss.includes(".msg-copy-btn {\n    order: 10") && overridesCss.includes(".msg-continue-btn,\n  .msg-edit-btn {\n    order: 20") && overridesCss.includes(".msg-verify-btn {\n    order: 21") && overridesCss.includes(".msg-export-btn {\n    order: 22") && overridesCss.includes(".msg-more-actions {\n    display: inline-flex") && overridesCss.includes("order: 30") && overridesCss.includes(".msg-regen-btn,\n  .msg-del-btn {\n    order: 40"));
assert("message edit and delete persist after DOM mutation", chatSrc.includes("function persistChatAfterDomMutation") && chatSrc.includes("saveChatHistory();\n  saveCurrentConversation();") && chatSrc.includes("persistChatAfterDomMutation();\n      }\n      showToast(t(\"chat.editLoaded\")") && chatSrc.includes("if (delBtn.disabled) return") && chatSrc.includes('delBtn.setAttribute("aria-busy", "true")') && chatSrc.includes("msg.remove();\n        persistChatAfterDomMutation();"));
assert("message regenerate uses guarded shared handler", chatMessageActionsControllerSrc.includes("function previousUserPromptForMessage") && chatMessageActionsControllerSrc.includes("async function startRegenerateMessage") && chatMessageActionsControllerSrc.includes('showToast(t("chat.regenerateMissingPrompt"), "warning", 2200)') && chatSrc.includes('regenBtn.addEventListener("click", () => startRegenerateMessage(regenBtn, msg))') && chatSrc.includes('regenBtn.addEventListener("click", () => startRegenerateMessage(regenBtn, msgEl, text))') && chatMessageActionsControllerSrc.includes('btn.setAttribute("aria-busy", "true")') && chatMessageActionsControllerSrc.includes("btn.removeAttribute(\"aria-busy\")") && i18nDe.includes('"chat.regenerateMissingPrompt"') && i18nEn.includes('"chat.regenerateMissingPrompt"'));
assert("memory cards are keyboard accessible and named", memorySrc.includes("function bindMemoryCardAction") && memorySrc.includes('el.setAttribute("role", "button")') && memorySrc.includes('el.setAttribute("tabindex", "0")') && memorySrc.includes("memory.openNoteLabel") && memorySrc.includes("memory.useSnippetLabel") && memorySrc.includes("memory.copyClipboardLabel"));
assert("memory destructive and toggle controls expose state", memorySrc.includes('delBtn.type = "button"') && memorySrc.includes("memory.deleteNoteLabel") && memorySrc.includes('deleteBtn.type = "button"') && memorySrc.includes("memory.deleteSnippetLabel") && memorySrc.includes('toggle.setAttribute("aria-pressed"') && memorySrc.includes("memory.toggleRoutineLabel"));
assert("memory card focus reveals nested actions", overridesCss.includes('.note-card[role="button"]:focus-visible') && overridesCss.includes(".note-card:focus-within .note-delete-btn") && overridesCss.includes(".snippet-card:focus-within .snippet-delete") && overridesCss.includes(".routine-toggle:focus-visible"));
assert("command list cards are keyboard accessible", commandsSrc.includes("function bindCommandItemAction") && commandsSrc.includes('el.setAttribute("role", "button")') && commandsSrc.includes('el.setAttribute("tabindex", "0")') && commandsSrc.includes("bindCommandItemAction(item") && commandsSrc.includes("cmd.insertCommandLabel"));
assert("command copy buttons are named and focus-visible", commandsSrc.includes('copyBtn.type = "button"') && commandsSrc.includes('const copyLabel = t("cmd.copyCommandLabel"') && commandsSrc.includes("copyBtn.title = copyLabel") && overridesCss.includes(".cmd-item:focus-visible") && overridesCss.includes(".cmd-item:focus-within .cmd-copy-btn"));
assert("command search input is named", commandsSrc.includes('id="cmd-search"') && commandsSrc.includes('aria-label="${escapeHtml(t("commands.search"))}"'));
assert("todo action buttons expose stable labels", productivitySrc.includes('checkBtn.type = "button"') && productivitySrc.includes("productivity.completeTodoLabel") && productivitySrc.includes('progressBtn.type = "button"') && productivitySrc.includes("productivity.markTodoInProgressLabel") && productivitySrc.includes('delBtn.type = "button"') && productivitySrc.includes("productivity.deleteTodoLabel"));
assert("todo titles can be edited from keyboard", productivitySrc.includes('titleEl.setAttribute("role", "button")') && productivitySrc.includes('titleEl.setAttribute("tabindex", "0")') && productivitySrc.includes("productivity.editTodoLabel") && productivitySrc.includes('event.key === "Enter" || event.key === " "') && overridesCss.includes('.todo-title[role="button"]:focus-visible'));
assert("habit buttons expose stable labels after template render", productivitySrc.includes('logBtn.type = "button"') && productivitySrc.includes("productivity.logHabitLabel") && productivitySrc.includes('deleteBtn.type = "button"') && productivitySrc.includes("productivity.deleteHabitLabel"));
assert("productivity export date follows active locale", productivitySrc.includes("function productivityLocale") && productivitySrc.includes("function productivityFormatDate") && productivitySrc.includes("toLocaleDateString(productivityLocale())") && productivitySrc.includes("productivityFormatDate()") && !productivitySrc.includes('toLocaleDateString("de-DE")'));
assert("pomodoro start and stop controls are localized", productivitySrc.includes('startBtn.textContent = t("productivity.startBtn")') && productivitySrc.includes('stopBtn.textContent = t("productivity.stopBtn")') && productivitySrc.includes('startBtn.setAttribute("aria-label", t("productivity.startBtn"))') && productivitySrc.includes('stopBtn.setAttribute("aria-label", t("productivity.stopBtn"))') && i18nDe.includes('"productivity.stopBtn"') && i18nEn.includes('"productivity.stopBtn"') && !productivitySrc.includes('textContent = "Start"') && !productivitySrc.includes('textContent = "Stop"'));
assert("productivity dynamic buttons set explicit type", productivityButtonsWithoutType.length === 0, productivityButtonsWithoutType.map((m) => `offset ${m.index}`).join(", "));
assert("all dynamic frontend buttons set explicit type", dynamicButtonsWithoutType.length === 0, dynamicButtonsWithoutType.join(", "));
assert("all static/template frontend buttons set explicit type", staticButtonsWithoutType.length === 0, staticButtonsWithoutType.join(", "));
assert("all static/template icon buttons expose an accessible name", staticIconButtonsWithoutName.length === 0, staticIconButtonsWithoutName.join(", "));
assert("all static/template form fields expose an accessible name", staticFormFieldsWithoutName.length === 0, staticFormFieldsWithoutName.join(", "));
assert("core modals expose dialog semantics and named close buttons", modalsSrc.includes('panel.setAttribute("role", "dialog")') && modalsSrc.includes('panel.setAttribute("aria-modal", "true")') && modalsSrc.includes('closeBtn.setAttribute("aria-label", t("common.close"))') && modalsSrc.includes('shortcuts-panel" role="dialog"') && memorySrc.includes('panel.setAttribute("role", "dialog")') && memorySrc.includes('panel.setAttribute("aria-modal", "true")') && memorySrc.includes("notes.editNote") && productivitySrc.includes('panel.setAttribute("role", "dialog")') && productivitySrc.includes('panel.setAttribute("aria-modal", "true")') && productivitySrc.includes("productivity.newTodoTitle") && productivitySrc.includes("productivity.startPomodoroTitle") && productivitySrc.includes("productivity.newHabitTitle") && i18nDe.includes('"notes.editNote"') && i18nEn.includes('"notes.editNote"'));
assert("core modal overlays trap tab focus", modalsSrc.includes("function getFocusableElements") && modalsSrc.includes("function trapFocusIn") && modalsSrc.includes("trapFocusIn(panel, e)") && modalsSrc.includes('e.key === "Tab"') && modalsSrc.includes("getClientRects().length > 0"));
assert("hero typography avoids viewport-scaled type and negative tracking", !overridesCss.includes("font-size: clamp") && !overridesCss.includes("letter-spacing: -"));
assert("ambient start view avoids landing-page hero treatment", overridesCss.includes(".greeting-title") && overridesCss.includes("font-size: 30px") && overridesCss.includes("-webkit-text-fill-color: currentColor") && overridesCss.includes(".talk-to-lexa-btn") && overridesCss.includes("width: 180px") && overridesCss.includes("height: 180px") && overridesCss.includes("box-shadow: none"));
assert("navigation chrome uses calmer product styling", overridesCss.includes(".sidebar-btn.active") && overridesCss.includes("background: rgba(91, 124, 250, 0.12)") && overridesCss.includes(".titlebar") && overridesCss.includes("background: rgba(9, 9, 16, 0.96)"));
assert("navigation keeps assistant and more areas directly visible without a more-less toggle", !html.includes('id="sidebar-more-toggle"') && !html.includes("sidebar-btn advanced-nav") && !html.includes("advanced-nav-section") && !src.includes("function setAdvancedNavOpen") && !src.includes("toggleAdvancedNav") && !overridesCss.includes(".sidebar:not(.advanced-open) .advanced-nav") && !i18nDe.includes('"nav.more"') && !i18nDe.includes('"nav.less"') && !i18nEn.includes('"nav.more"') && !i18nEn.includes('"nav.less"') && html.includes('data-i18n="sidebar.main"') && html.includes('data-i18n="sidebar.tools"'));
assert("transient notifications avoid glow-heavy demo chrome", overridesCss.includes(".toast {") && overridesCss.includes("box-shadow: 0 18px 42px rgba(0, 0, 0, 0.3)") && overridesCss.includes(".notif-center") && overridesCss.includes("box-shadow: 0 18px 46px rgba(0, 0, 0, 0.34)"));
assert("chat transcript bubbles use calmer professional surfaces", overridesCss.includes(".system-message .msg-text") && overridesCss.includes("background: rgba(255, 255, 255, 0.032)") && overridesCss.includes(".user-message .msg-text") && overridesCss.includes("background: rgba(91, 124, 250, 0.12)") && overridesCss.includes("backdrop-filter: none"));
assert("chat suggestion chips avoid glow-heavy demo styling", overridesCss.includes(".suggestion-chip") && overridesCss.includes("border-radius: 8px") && overridesCss.includes("transform: none") && overridesCss.includes("box-shadow: none"));
assert("dashboard widgets avoid hero-glow demo styling", overridesCss.includes(".dash-widget-greeting::before") && overridesCss.includes("display: none") && overridesCss.includes(".dash-clock") && overridesCss.includes("-webkit-text-fill-color: currentColor") && overridesCss.includes(".dash-chat-btn:hover") && overridesCss.includes("box-shadow: none"));
assert("system tool cards use dense professional rows", overridesCss.includes(".tool-card") && overridesCss.includes("grid-template-columns: 36px minmax(0, 1fr)") && overridesCss.includes("min-height: 72px") && overridesCss.includes(".tool-icon") && overridesCss.includes("font-size: 15px"));
assert("dashboard greeting avoids boss/demo address", !html.includes("Guten Tag, Chef") && !i18nDe.includes("Chef!") && !i18nEn.includes("Boss!"));
assert("ambient canvas is initialized as a real animated surface", html.includes('id="lexa-ambient-canvas"') && src.includes("function initLexaAmbientCanvas") && src.includes("window.__lexaAmbientDebug") && overridesCss.includes(".lexa-ambient-canvas"));
assert("global command palette exposes dialog and listbox semantics", modalsSrc.includes('class="cmd-palette" role="dialog" aria-modal="true"') && modalsSrc.includes('aria-label="${escapeHtml(t("palette.title"))}"') && modalsSrc.includes('aria-controls="palette-results"') && modalsSrc.includes('role="listbox"') && modalsSrc.includes('el.setAttribute("role", "option")') && modalsSrc.includes('el.setAttribute("aria-selected"') && modalsSrc.includes('aria-activedescendant') && i18nDe.includes('"palette.title"') && i18nEn.includes('"palette.title"'));
assert("global command palette restores and traps focus", modalsSrc.includes("let _paletteRestoreFocusEl = null") && modalsSrc.includes("function restoreFocus") && modalsSrc.includes("_paletteRestoreFocusEl = active") && modalsSrc.includes("closePalette(options = {})") && modalsSrc.includes('options.restoreFocus !== false') && modalsSrc.includes('removeAttribute("aria-activedescendant")') && modalsSrc.includes("closePalette({ restoreFocus: false })") && modalsSrc.includes("trapFocusIn(paletteEl, e)"));
assert("shortcuts overlay restores and traps focus on dismiss", modalsSrc.includes("const restoreFocusEl = document.activeElement") && modalsSrc.includes("const closeShortcuts = () =>") && modalsSrc.includes("restoreFocus(restoreFocusEl)") && modalsSrc.includes('addEventListener("click", closeShortcuts)') && modalsSrc.includes("trapFocusIn(overlay, e)") && modalsSrc.includes('document.getElementById("shortcuts-close-btn")?.focus()'));
assert("chat composer exposes a command palette", html.includes('id="composer-command-btn"') && html.includes('id="composer-command-palette"') && chatComposerSrc.includes("LEXA_COMPOSER_COMMANDS") && chatSrc.includes("handleComposerCommandKeydown") && src.includes("setupComposerCommandPalette"));
assert("composer command palette exposes listbox active-descendant state", html.includes('id="composer-command-palette"') && html.includes('role="listbox"') && html.includes('aria-hidden="true"') && html.includes('id="composer-command-btn"') && html.includes('aria-haspopup="listbox"') && html.includes('id="chat-input"') && html.includes('aria-controls="composer-command-palette"') && html.includes('aria-expanded="false"') && html.includes('aria-autocomplete="list"') && chatSrc.includes("function updateComposerCommandActiveDescendant") && chatSrc.includes('chatInput.setAttribute("aria-activedescendant"') && chatSrc.includes("composer-command-option-${command.id}") && chatSrc.includes('row.setAttribute("aria-label", `${label}: ${desc}. ${prefixHint}`)') && chatSrc.includes('aria-hidden="true">${composerCommandIconSvg') && chatSrc.includes('button.setAttribute("aria-haspopup", "listbox")') && chatSrc.includes('e.key !== "ArrowDown"') && overridesCss.includes(".composer-command-item:focus-visible"));
assert("composer command palette copy is localized", html.includes('data-i18n-aria-label="composer.paletteLabel"') && html.includes('data-i18n-aria-label="composer.buttonLabel"') && html.includes('data-i18n-title="composer.buttonTitle"') && html.includes('data-i18n-aria-label="chat.enterMessage"') && chatComposerSrc.includes("function composerCommandText") && chatComposerSrc.includes("composerCommandPrefix(command)") && chatSrc.includes('t("composer.empty")') && chatSrc.includes('t("composer.readyToast", { label })') && i18nDe.includes('"composer.improve.prefix"') && i18nEn.includes('"composer.improve.prefix"') && i18nDe.includes('"composer.readyToast"') && i18nEn.includes('"composer.readyToast"'));
assert("composer includes clone, figma, and page commands from requested UI", chatComposerSrc.includes('id: "clone"') && chatComposerSrc.includes('id: "figma"') && chatComposerSrc.includes('id: "page"') && chatComposerSrc.includes('icon: "figma"') && chatComposerSrc.includes('icon: "monitor"') && i18nDe.includes('"composer.clone.prefix"') && i18nEn.includes('"composer.figma.prefix"') && i18nDe.includes('"composer.page.prefix"'));
assert("composer exposes research, workspace, context, draft review, skill, deep think, and ship workflows", chatComposerSrc.includes('id: "research"') && chatComposerSrc.includes('id: "workspace"') && chatComposerSrc.includes('id: "context"') && chatComposerSrc.includes('id: "review"') && chatComposerSrc.includes('id: "skill"') && chatComposerSrc.includes('id: "think"') && chatComposerSrc.includes('id: "ship"') && chatComposerSrc.includes('icon: "search"') && chatComposerSrc.includes('icon: "doc"') && chatComposerSrc.includes('icon: "layers"') && chatComposerSrc.includes('icon: "check"') && chatComposerSrc.includes('icon: "wand"') && chatComposerSrc.includes('icon: "brain"') && chatComposerSrc.includes('icon: "rocket"') && i18nDe.includes('"composer.research.prefix"') && i18nEn.includes('"composer.research.prefix"') && i18nDe.includes('"composer.workspace.prefix"') && i18nEn.includes('"composer.workspace.prefix"') && i18nDe.includes('"composer.context.prefix"') && i18nEn.includes('"composer.context.prefix"') && i18nDe.includes('"composer.review.prefix"') && i18nEn.includes('"composer.review.prefix"') && i18nDe.includes('"composer.skill.prefix"') && i18nEn.includes('"composer.skill.prefix"') && i18nDe.includes('"composer.think.prefix"') && i18nEn.includes('"composer.think.prefix"') && i18nDe.includes('"composer.ship.prefix"') && i18nEn.includes('"composer.ship.prefix"') && i18nDe.includes('quellenbasierten Research-Brief') && i18nEn.includes('source-backed research brief') && i18nEn.includes('Personal OS context pack') && i18nEn.includes('pending drafts') && i18nEn.includes('reusable Lexa Skill') && i18nEn.includes('decision brief') && i18nEn.includes('release readiness'));
assert("composer workflows expose distinct slash aliases", chatComposerSrc.includes('hint: "/research"') && chatComposerSrc.includes('hint: "/workspace"') && chatComposerSrc.includes('hint: "/context"') && chatComposerSrc.includes('hint: "/review"') && chatComposerSrc.includes('hint: "/skill"') && chatComposerSrc.includes('hint: "/think"') && chatComposerSrc.includes('hint: "/ship"') && chatComposerSrc.includes('"rb"') && chatComposerSrc.includes('"ws"') && chatComposerSrc.includes('"ctx"') && chatComposerSrc.includes('"rv"') && chatComposerSrc.includes('"sk"') && chatComposerSrc.includes('"dt"') && chatComposerSrc.includes('"rl"') && chatComposerSrc.includes("function expandComposerSlashAlias") && chatSrc.includes("expandComposerSlashAlias(rawText)") && chatComposerSrc.includes("composerCommandForAlias(match[1], { allowPrefix: true })") && chatComposerSrc.includes("const primary = command?.hint || composerCommandPrefix(command)"));
assert("composer workflow search ranks aliases before prompt text", chatComposerSrc.includes("function composerCommandScore") && chatComposerSrc.includes("function composerCommandSearchItems") && chatComposerSrc.includes("aliases.some((alias) => alias === q)") && chatComposerSrc.includes("b.score - a.score") && chatSrc.includes("composerCommandSearchItems(query)"));
assert("composer workflow aliases normalize user spelling", chatComposerSrc.includes("function composerCommandAliasKey") && chatComposerSrc.includes('"ae"') && chatComposerSrc.includes('"oe"') && chatComposerSrc.includes('"ue"') && chatComposerSrc.includes('"ss"') && chatComposerSrc.includes('.replace(/[\\s_-]+/g, "")') && chatComposerSrc.includes("composerCommandForAlias(match[1], { allowPrefix: true })"));
assert("composer workflow alias expansion accepts only unique prefixes", chatComposerSrc.includes("function composerCommandForAlias") && chatComposerSrc.includes("const allowPrefix = Boolean(options?.allowPrefix)") && chatComposerSrc.includes("prefixMatches.length === 1") && chatComposerSrc.includes("value.startsWith(key)"));
assert("composer workflow hints surface short aliases", chatComposerSrc.includes("function composerCommandHintText") && chatComposerSrc.includes("shortAliases.find((value) => value.length > 1)") && chatSrc.includes('row.title = `${label}: ${desc} (${prefixHint})`') && chatSrc.includes("composerCommandHintText(command)"));
assert("composer workflow search resets stale selection on new query", chatSrc.includes("let _composerCommandLastQuery") && chatSrc.includes("const normalizedQuery = composerCommandAliasKey(query)") && chatSrc.includes("normalizedQuery !== _composerCommandLastQuery") && chatSrc.includes("_composerCommandIdx = 0"));
assert("composer placeholder rotation stays simple while workflows remain in the slash palette", src.includes('t("app.placeholderSimpleWrite")') && src.includes('t("app.placeholderSimpleResearch")') && src.includes('t("app.placeholderSimplePlan")') && src.includes('t("app.placeholderSimpleScreen")') && !src.includes('t("app.placeholderGit")') && !src.includes('t("app.placeholderShipCheck")') && i18nDe.includes('"app.placeholderSimpleWrite"') && i18nEn.includes('"app.placeholderSimpleWrite"'));
assert("composer command palette has professional product styling", overridesCss.includes(".composer-command-palette") && overridesCss.includes(".composer-command-item") && overridesCss.includes("grid-template-columns: 34px minmax(0, 1fr) auto"));
assert("chat view does not poll system stats every few seconds", src.includes('if (view !== "dashboard" && view !== "system") return;'));
assert("system info requests are cached across dashboard and system views", src.includes("let _systemInfoPromise") && src.includes("async function requestSystemInfoCached") && src.includes("window.requestSystemInfoCached = requestSystemInfoCached") && dashboardSrc.includes("window.requestSystemInfoCached({ maxAgeMs: 12000 })") && systemSrc.includes("window.requestSystemInfoCached({ maxAgeMs: 5000, force: true })"));
assert("electron visual smoke uses mocked backend bridge", preloadSrc.includes('process.env.LEXA_ELECTRON_SMOKE_MOCK === "1"') && preloadSrc.includes('API_BASE: "mock://lexa-smoke"') && preloadSrc.includes("conversationCreate: async") && preloadSrc.includes("wakewordStart: async") && fs.readFileSync(path.join(__dirname, "electron_ui_visual_smoke.js"), "utf8").includes('process.env.LEXA_ELECTRON_SMOKE_MOCK = "1"'));
assert("startup logs keep optional integrations quiet", calendarIntegrationSrc.includes("logger.debug(\"Google Calendar client secret not configured") && !calendarIntegrationSrc.includes("logger.error(\"Client secret file not found") && toolHealthSrc.includes("logger.debug(f\"Tool health:") && toolHealthSrc.includes("logger.debug(f\"Missing optional tools:"));
assert("plugin sandbox allows safe re.compile web-search parsing", pluginManagerSrc.includes("_FORBIDDEN_REGEX_PATTERNS") && !pluginManagerSrc.includes('    "compile(",\n') && pluginManagerSrc.includes('(?<![\\w.])compile\\s*\\('));
assert("global search overlay is named as a dialog", chatSrc.includes('class="search-panel" role="dialog" aria-modal="true"') && chatSrc.includes('aria-label="${escapeHtml(t("nav.searchTooltip"))}"') && chatSrc.includes('id="search-input"') && chatSrc.includes('aria-label="${escapeHtml(t("chat.searchPlaceholder"))}"') && chatSrc.includes('id="search-close-btn"') && chatSrc.includes('aria-label="${escapeHtml(t("common.close"))}"'));
assert("global search restores focus, traps focus, and has keyboard results", chatSrc.includes("let searchRestoreFocusEl = null") && chatSrc.includes("function restoreSearchFocus") && chatSrc.includes("function trapSearchFocus") && chatSrc.includes("searchRestoreFocusEl = active") && chatSrc.includes("closeSearchOverlay(options = {})") && chatSrc.includes("trapSearchFocus(overlay, e)") && chatSrc.includes('item.setAttribute("role", "button")') && chatSrc.includes('item.setAttribute("tabindex", "0")') && chatSrc.includes('event.key === "Enter" || event.key === " "') && overridesCss.includes(".search-item:focus-visible"));
assert("notification center rows use denser message styling", overridesCss.includes(".notif-item") && overridesCss.includes("grid-template-columns: 34px minmax(0, 1fr) auto") && overridesCss.includes(".notif-item-time"));
assert("app-wide UI QA pass bounds operational views", overridesCss.includes("App-wide UI QA pass") && overridesCss.includes(".tool-view > .view-title") && overridesCss.includes("width: min(100%, 1120px)") && overridesCss.includes("#personal-os-view > .pos-shell"));
assert("section headers and action rows wrap instead of overflowing", overridesCss.includes(".section-header") && overridesCss.includes("flex-wrap: wrap") && overridesCss.includes(".flex-row-nowrap") && overridesCss.includes("justify-content: flex-end"));
assert("settings rows use responsive grid layout", overridesCss.includes(".setting-item") && overridesCss.includes("grid-template-columns: minmax(0, 1fr) max-content") && overridesCss.includes("@media (max-width: 720px)") && overridesCss.includes("grid-template-columns: 1fr"));
assert("settings controls are bounded and focus-visible", overridesCss.includes(".settings-select,") && overridesCss.includes("max-width: min(340px, 44vw)") && overridesCss.includes("box-shadow: 0 0 0 3px rgba(139, 146, 255, 0.12)"));
assert("accent swatches are named pressed-state controls", html.includes('class="accent-dot active') && html.includes('aria-pressed="true"') && html.includes('data-i18n-aria-label="settings.purple"') && html.includes('data-i18n-aria-label="settings.gold"') && settingsSrc.includes('d.setAttribute("aria-pressed"'));
assert("settings and productivity selects expose localized labels", html.includes('id="todo-filter"') && html.includes('data-i18n-aria-label="productivity.todoFilter"') && html.includes('id="model-select"') && html.includes('data-i18n-aria-label="settings.aiModel"') && html.includes('id="el-voice-select"') && html.includes('data-i18n-aria-label="settings.voice"') && html.includes('id="stt-model-select"') && html.includes('data-i18n-aria-label="settings.sttModel"') && i18nDe.includes('"productivity.todoFilter"') && i18nEn.includes('"productivity.todoFilter"'));
assert("global empty and modal states share calmer product chrome", overridesCss.includes(".empty-state,") && overridesCss.includes(".search-panel,") && overridesCss.includes("box-shadow: 0 24px 64px rgba(0, 0, 0, 0.42)"));

console.log(`\n${passed + failed} tests: ${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
