/* ════════════════════════════════════════════════
   LEXA AI — Frontend Configuration
   All magic numbers and configurable values.
   ════════════════════════════════════════════════ */

const LexaConfig = Object.freeze({
  // API
  API_BASE: "http://127.0.0.1:8000",
  FETCH_TIMEOUT: 30000,

  // Polling intervals (ms)
  HEALTH_CHECK_INTERVAL: 8000,
  SYSTEM_STATS_INTERVAL: 5000,
  AUTO_SAVE_INTERVAL: 60000,
  TIMER_CHECK_INTERVAL: 5000,
  DASHBOARD_REFRESH_INTERVAL: 10000,
  MEMORY_REFRESH_INTERVAL: 30000,
  CLOCK_INTERVAL: 1000,
  PLACEHOLDER_ROTATE_INTERVAL: 8000,
  WAKEWORD_POLL_INTERVAL: 500,
  WAKEWORD_FAST_POLL_INTERVAL: 150,
  CONV_POLL_INTERVAL: 150,

  // Chat
  MAX_CHAT_INPUT_LENGTH: 4000,
  CHAT_HISTORY_LOCAL_MAX: 80,
  CHAT_INPUT_HISTORY_MAX: 50,
  MAX_DOM_MESSAGES: 100,

  // Notifications
  TOAST_DURATION_DEFAULT: 5000,
  TOAST_DURATION_SHORT: 2000,
  TOAST_DURATION_LONG: 8000,

  // UI
  CHAR_COUNTER_WARN: 3000,
  CHAR_COUNTER_DANGER: 3800,
  DEBOUNCE_VIEW_REFRESH: 200,
  SEARCH_DEBOUNCE: 300,

  // Reconnect
  WAKEWORD_RETRY_DELAY: 2000,
  WAKEWORD_MAX_RETRIES: 3,

  // Voice WebSocket
  VOICE_WS_RECONNECT_DELAY: 1000,
  VOICE_WS_MAX_QUEUE: 1000,
});
